### ISSUE TITLE
为什么同样的size，分别使用ui、cg、io这三种方式压缩的图片分辨率都不同的？

### ISSUE THREAD

**Issue by Rogue24** [woshiccm/ImageResizing#1]
如题，也就ui的方式最符合，cg最模糊，而io压根没压缩过

**Comment by Rogue24** [comment]
哦，发现了，你的imageIO方法里面用的是CGImageSourceCreateImageAtIndex，而不是CGImageSourceCreateThumbnailAtIndex

**Comment by Rogue24** [comment]
好像是ui方法里面用到了UIGraphicsBeginImageContextWithOptions，这里的scale在不同机型系统使用的不同值，而cg和io方法得到图片则是ui方法在sclae为 1 的情况下的清晰度，所以这个方法得到的图片清晰度不一样，请问怎么在cg和io方法中也能根据这个scale来进行压缩呢？

**Comment by woshiccm** [comment]
这个目前我也不知道呢，可能没提供这样的接口吧
